[WIP] feat: add full screen ad hooks
invertase/react-native-google-mobile-ads pull request #100
Opened 2022-03-19 14:51 UTC by wjaykim

### Description

This PR add supports for hook-style ad state management which can be used for full screen ads(AppOpen, Interstitial, Rewarded). This feature is initially implemented in another admob library, [@react-native-admob/admob](https://github.com/react-native-admob/admob).
I'm happy to join forces on this single package which can be maintained better😁.

### Related issues

### Release Summary

add full screen ad hooks

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [ ] No

### Test Plan

---

Think `react-native-google-mobile-ads` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

2022-03-19 14:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/invertase/react-native-google-mobile-ads?pullRequest=100) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/invertase/react-native-google-mobile-ads?pullRequest=100) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/invertase/react-native-google-mobile-ads?pullRequest=100) it.</sub>

2022-03-19 15:23 UTC, mikehardy commented
@wjaykim welcome welcome 👋 😄  I really excited personally to (hopefully) have everyone join forces in one library we can all tag-team on so as maintainers we all have just a little to do instead of everyone having to do everything. I'll queue this for review and hopefully the vision of one great admob package and a reasonable work load for everyone can become a reality :)

2022-04-08 15:21 UTC, dylancom requested changes

2022-04-08 15:21 UTC, dylancom commented on docs/displaying-ads-hook.mdx
> +The AdMob package provides hooks to help you to display ads in functional component with tiny code. The supported ad formats are full-screen-type-ads: AppOpen, Interstitial, Rewarded.
```suggestion
The AdMob package provides hooks to help you to display ads in a functional component with tiny code. The supported ad formats are full-screen ads: App open, Interstitial & Rewarded.
```

2022-04-08 15:21 UTC, dylancom commented on docs/displaying-ads-hook.mdx
> +## Creating ad
```suggestion
## Load an ad
```

2022-04-08 15:21 UTC, dylancom commented on docs/displaying-ads-hook.mdx
> +## Displaying ad
```suggestion
## Show the ad
```

2022-04-08 15:21 UTC, dylancom commented on docs/displaying-ads-hook.mdx
> +> `adUnitid` parameter is also can be used to manage creation and destruction of ad instance.
```suggestion
> The `adUnitid` parameter can also be used to manage creation and destruction of an ad instance.
```

2022-04-08 15:21 UTC, dylancom commented on docs/displaying-ads-hook.mdx
> +The second argument is additional optional request options object to be sent whilst loading an advert, such as keywords & location.
```suggestion
The second argument is an additional optional request options object to be sent whilst loading an advert, such as keywords & location.
```

2022-04-08 15:21 UTC, dylancom commented on src/hooks/useAppOpenAd.ts
> +      //prevAd?.destroy();
```suggestion
```

2022-04-08 15:21 UTC, dylancom commented on src/hooks/useInterstitialAd.ts
> +      //prevAd?.destroy();
```suggestion
```

2022-04-08 15:21 UTC, dylancom commented on src/hooks/useRewardedAd.ts
> +      //prevAd?.destroy();
```suggestion
```

2022-04-08 18:42 UTC, mikehardy approved these changes
Looks great to me, and @dylancom just had language comments which I went ahead and just committed, since it seemed best to do a squash merge anyway since it's one feature all at once effectively

I'll pull locally, check the example and assuming it looks good merge this

2022-04-08 18:47 UTC, dylancom approved these changes

2022-04-08 19:50 UTC, mikehardy commented
I tested it locally and everything works - I actually extended the test app a bit to test all 3 of the hooks and they're all good.
I would have included that as a new commit on this PR but I think I saw an error that testing exposed, so I'll do it as another PR.

So this is good to go --> @wjaykim :trophy: :bow:

2022-04-08 19:52 UTC, merged

2022-04-16 23:53 UTC, mikehardy commented
:tada: This PR is included in version 5.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-google-mobile-ads/v/5.1.0)
- [GitHub release](https://github.com/invertase/react-native-google-mobile-ads/releases/tag/v5.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: