feat(hooks): automatically set isLoaded to false
invertase/react-native-google-mobile-ads pull request #199
Opened 2022-07-30 12:03 UTC by jeremyhalin

### Description

I find it weird that `isLoaded` in hooks doesn't change value when ad is shown. In fact, the value `isLoaded = true` after ad has been shown is wrong since a new ad has not been loaded and calling `show` will fail.

### Related issues

### Release Summary

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- ~~My change includes tests;~~
  - [ ] ~~`e2e` tests added or updated in `__tests__e2e__`~~
  - [ ] ~~`jest` tests added or updated in `__tests__`~~
- [ ] ~~I have updated TypeScript types that are affected by my change.~~
- This is a breaking change;
  - [ ] ~~Yes~~
  - [x] No

### Test Plan

I wanted to add some tests on `useRewardedAd` hook but I had this error
```bash
    TypeError: RNAppModule.eventsNotifyReady is not a function

      34 |   ) {
      35 |     if (!this.ready) {
    > 36 |       RNAppModule.eventsNotifyReady(true);
         |                   ^
      37 |       this.ready = true;
      38 |     }
      39 |     RNAppModule.eventsAddListener(eventType);

      at GANativeEventEmitter.eventsNotifyReady [as addListener] (src/internal/GoogleMobileAdsNativeEventEmitter.ts:36:19)
      at addListener (src/internal/registry/nativeModule.ts:146:39)
      at subscribeToNativeModuleEvent (src/internal/registry/nativeModule.ts:124:7)
      at initialiseNativeModule (src/internal/registry/nativeModule.ts:203:10)
      at MobileAdsModule.get (src/internal/Module.ts:52:26)
      at MobileAdsModule.native [as initialize] (src/MobileAds.ts:57:17)
      at initialize (__tests__/rewarded.test.tsx:7:19)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:119:21)
```

`rewarded.test.tsx`
```typescript
import { renderHook, act } from '@testing-library/react-hooks/native';
import MobileAds, { useRewardedAd } from '../src';

describe('Admob Rewarded', () => {
  describe('useRewardedAd() hook', function () {
    it('has false as isLoaded initial value', async function () {
      MobileAds().initialize();
      const { result } = renderHook(() => useRewardedAd('123'));

      expect(result.current.isLoaded).toBe(false);

      act(() => {
        result.current.load();
      });

      expect(result.current.isLoaded).toBe(true);
    });
  });
});
```

And I had plan to test if calling `show` will set `isLoaded` to `false`.

---

Think `react-native-google-mobile-ads` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

🔥

2022-07-30 12:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/invertase/react-native-google-mobile-ads?pullRequest=199) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/invertase/react-native-google-mobile-ads?pullRequest=199) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/invertase/react-native-google-mobile-ads?pullRequest=199) it.</sub>

2022-08-10 05:34 UTC, Jongkeun commented
I have the same issue. 
I think, after showing ad and `isLoaded` value should be false because we've already used the loaded ad. 
But it's still true.

2022-09-02 12:20 UTC, dylancom commented
I think we should set isLoaded to false upon closing the ad.
(Just like we already do in the MobileAd class, where you can access `adInstance.loaded` when not using hooks)
See: https://github.com/invertase/react-native-google-mobile-ads/blob/main/src/ads/MobileAd.ts#L98
@wjaykim what do you think?

2022-09-02 13:01 UTC, wjaykim commented
I agree. It was weird behavior. Let's make it change, but it's a breaking change, so we will have to increase major version.

2022-09-02 14:27 UTC, dylancom requested changes

2022-09-02 14:27 UTC, dylancom commented on src/hooks/useFullScreenAd.ts
> +          setState({ isOpened: true, isLoaded: false });
Please align with: https://github.com/invertase/react-native-google-mobile-ads/blob/main/src/ads/MobileAd.ts#L98
Where we reset loaded after closing.

2022-09-02 14:27 UTC, dylancom commented on docs/displaying-ads-hook.mdx
> +| isLoaded       | boolean                            | Whether the ad is loaded and ready to to be shown to the user. Automatically set to false when the ad is opened.   |
I think we can leave the original text untouched or change to something like "Automatically set to `false` when the ad was shown.".

2022-09-06 10:53 UTC, dylancom approved these changes

2022-09-06 11:01 UTC, dylancom commented
Thanks for your contribution!

2022-09-06 11:27 UTC, merged

2022-09-06 12:03 UTC, mikehardy commented
:tada: This PR is included in version 8.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-google-mobile-ads/v/8.0.0)
- [GitHub release](https://github.com/invertase/react-native-google-mobile-ads/releases/tag/v8.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: