fix(banner, android): support props for multiple view instances
invertase/react-native-google-mobile-ads pull request #305
Opened 2023-01-04 08:21 UTC by aidan-24com

### Description

The Java class for `ReactNativeGoogleMobileAdsBannerAdViewManager` is a _single_ instance. It instantiates new `reactViewGroup` instances for _each_ JSX element that is rendered.

The Objective-C class `RNGoogleMobileAdsBannerViewManager` is instantiated for each JSX element.

This PR is to address the Java discrepancy, because when rendering multiple banners (on Android) the latest set props are used for the `reactViewGroup` instances.

### Related issues

I didn't file an issue for it.

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

Render multiple Banners in a list (on android) with different props for each ad slot. The received ads will now render correctly with their respective options.

Previously, due to the asynchronous nature of the bridge, ad slots that where already instantiated would start to use the latest set props.

---

:fire:

2023-01-04 13:00 UTC, aidan-24com commented
apologies, I'll run the linter and update the PR shortly

2023-02-09 09:05 UTC, aidan-24com commented
pinging a maintainer as requested above

@mikehardy when you get a chance 👍

2023-02-12 07:46 UTC, dylancom commented
Could you explain why the adlistener on oldAdView is needed?

2023-02-13 12:48 UTC, aidan-24com commented
Apologies, the oldAdView adlisteners code was basically a straight copy of the code we had running on an old version of this package.

After testing it again, the oldAdView adlisteners are not required.

Initially there was an issue that the listeners for ad views that had been removed were triggering. This appears to no longer be the case, I have updated the PR.

2023-02-13 12:50 UTC, dylancom commented
Thanks and is it necessary to move the oldAdView.destroy() line?

2023-02-15 17:07 UTC, dylancom commented
I did a bit of research and found that we can extend the ReactViewGroup to avoid having to work with maps.
That way we can directly set the props on the extended ReactViewGroup instance, which seems a neater approach to me.

See: https://github.com/sbugert/react-native-admob/blob/master/android/src/main/java/com/sbugert/rnadmob/RNAdMobBannerViewManager.java#L28

And: https://github.com/sbugert/react-native-admob/blob/master/android/src/main/java/com/sbugert/rnadmob/RNAdMobBannerViewManager.java#L220

2023-02-15 17:20 UTC, dylancom requested changes

2023-02-15 17:20 UTC, dylancom commented on android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java
> +  private final HashMap<Integer, AdRequest> requestMap = new HashMap<>();
If we create a ReactAdView class that extends ReactViewGroup, we don't need maps to keep track of everything and set those props directly on the instance. See: https://github.com/sbugert/react-native-admob/blob/master/android/src/main/java/com/sbugert/rnadmob/RNAdMobBannerViewManager.java#L28

2023-02-20 07:42 UTC, dylancom commented
@aidan-24com is the requested change something you'd have time to do, or should I make a PR?

2023-02-20 07:54 UTC, aidan-24com commented
@dylancom I will attempt to get it in this week, since it is on my task list.

thanks for the offer. I might reach out, if things get too hectic

2023-02-22 14:20 UTC, aidan-24com commented
@dylancom when you have a moment, please take a look at the `ReactNativeAdView` implementation.

thanks

2023-02-22 14:35 UTC, dylancom commented
@aidan-24com was just testing it out on a real device.
Thanks a lot for bringing this up and your work! 🚀

2023-02-22 14:37 UTC, dylancom approved these changes

2023-02-22 14:38 UTC, merged

2023-02-22 15:18 UTC, mikehardy commented
:tada: This PR is included in version 9.1.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-google-mobile-ads/v/9.1.2)
- [GitHub release](https://github.com/invertase/react-native-google-mobile-ads/releases/tag/v9.1.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-22 15:32 UTC, mikehardy commented
Really cool - thanks @aidan-24com ! And also thanks to @dylancom for shepherding, really really appreciated