feat(debug): add debug module
invertase/react-native-google-mobile-ads pull request #306
Opened 2023-01-04 08:36 UTC by aidan-24com

### Description

Our in-house ad team need access to the Google Mobile Ads Debug Menu.

This PR is to have access to a `NativeModule` method to trigger the required Ad SDK method.

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

Render a button that onPress will call the Native Module's method with the ad's `unitId`

```ts
import { Debug } from 'react-native-google-mobile-ads'

…
Debug.openDebugMenu(props.adUnitID)
…

```

---

:fire:

2023-01-04 15:08 UTC, dylancom commented
Why not just make it a method on MobileAds directly (similar to the SDK).
So we can just call: mobileAds().openDebugMenu(props.adUnitID)

2023-01-04 15:23 UTC, dylancom requested changes

2023-01-04 15:23 UTC, dylancom commented on android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsDebugModule.java
> +                  MobileAds.initialize(getReactApplicationContext());
Is this extra initialize needed? I think we can leave this line out and just add a note to the interface that initialize has to be called before using this method.

2023-01-09 12:36 UTC, aidan-24com commented
Apologies, after chatting to our ad team, this feature is no longer needed. Abandoning this PR

2023-01-09 12:36 UTC, closed without merging