fix:  Solved issue with method recordManualImpression for GAMBannerAd
invertase/react-native-google-mobile-ads pull request #363
Opened 2023-04-11 13:28 UTC by amolrajoba

### Description
fix: for method ```recordManualImpression```  in ReactNativeGoogleMobileAdsBannerAdViewManager.java  
The Android Java code in ReactNativeGoogleMobileAdsBannerAdViewManager.java is expecting an Integer after ```Integer.parseInt``` but currently string 'recordManualImpression' is passed. 

### Related issues

### Release Summary

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-google-mobile-ads` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

2023-04-13 11:40 UTC, amolrajoba commented
> 
for iOS there is no comparison with the passed value in  "RNGoogleMobileAdsBannerViewManager.m" file. In Android there is 
comparison with the passed value after Integer.parseInt in "ReactNativeGoogleMobileAdsBannerAdViewManager.java".
```
    int commandIdInt = Integer.parseInt(commandId);

    if (commandIdInt == COMMAND_ID_RECORD_MANUAL_IMPRESSION) {
      BaseAdView adView = getAdView(reactViewGroup);
      if (adView instanceof AdManagerAdView) {
        ((AdManagerAdView) adView).recordManualImpression();
      }
    }
```
this kind of check not there in iOS code before native method call recordManualImpression() .

2023-04-13 11:59 UTC, dylancom requested changes
There are methods available to get the command id.

iOS: UIManager.getViewManagerConfig('RNGoogleMobileAdsBannerView').Commands.recordManualImpression
Android: UIManager.RNGoogleMobileAdsBannerView.Commands.recordManualImpression.toString()

See:
https://reactnative.dev/docs/native-components-ios#handling-multiple-native-views
https://reactnative.dev/docs/native-components-android#6-implement-the-javascript-module

2023-04-13 12:07 UTC, dylancom requested changes

2023-04-13 12:07 UTC, dylancom commented on src/ads/GAMBannerAd.tsx
> +      this.commonIDRecordManualImpression,
```suggestion
      Platform.OS === 'ios' ? 'recordManualImpression' : UIManager.RNGoogleMobileAdsBannerView.Commands.recordManualImpression.toString(),
```

2023-04-13 18:43 UTC, mikehardy approved these changes
Appears to match the docs based on my read of the docs vs this code, nice fix!

2023-04-13 18:45 UTC, merged

2023-04-13 20:26 UTC, mikehardy commented
:tada: This PR is included in version 10.1.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-google-mobile-ads/v/10.1.3)
- [GitHub release](https://github.com/invertase/react-native-google-mobile-ads/releases/tag/v10.1.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-05-02 20:49 UTC, ds8k commented
This change is causing the following redbox on simulator:
![Screenshot 2023-05-02 at 4 45 45 PM](https://user-images.githubusercontent.com/4458812/235782472-3099946f-9f87-443f-bed1-d12b84126e0e.png)

2023-05-03 07:20 UTC, dylancom commented
@ds8k thanks for the report! Should be fixed in 10.3.2