Null kontrolü yapıldı.
invertase/react-native-google-mobile-ads pull request #436
Opened 2023-08-22 11:20 UTC by Sygn53

### Description

### Related issues

### Release Summary

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [ ] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [ ] No

### Test Plan

---

Think `react-native-google-mobile-ads` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

2023-09-03 21:49 UTC, mikehardy reviewed
Interesting! This seems reasonable, the current Activity *can* go null in react-native apps due to the asynchronous nature of the react-native bridge. It is rare but it can happen.

So the code change seems valid although there is some spacing inconsistency (running `yarn lint:android`  (defined [here](https://github.com/invertase/react-native-google-mobile-ads/blob/1598969db5010afdc0850036bd10198c2d3e209f/package.json#L71)) and committing the result might fix it automatically?) and it would probably help developers to log a warning ("warning" level chosen because this is a serious problem that we cannot really handle without disabling functionality - we do not fetch an ad, for instance, but we can recover at least and not crash)

2023-09-04 08:16 UTC, dylancom requested changes

2023-09-04 08:16 UTC, dylancom commented on android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java
> +          // in order to display the debug menu for GAM ads we need the activity context
Please remove the duplicated comment:
```
// in order to display the debug menu for GAM ads we need the activity context
// https://github.com/invertase/react-native-google-mobile-ads/issues/188
```

2023-09-09 09:25 UTC, dylancom commented
Fixes #432

2023-09-09 10:21 UTC, merged

2023-09-11 10:32 UTC, mikehardy commented
:tada: This PR is included in version 12.1.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-google-mobile-ads/v/12.1.2)
- [GitHub release](https://github.com/invertase/react-native-google-mobile-ads/releases/tag/v12.1.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: