feat(android): Add support for ArrayList
invertase/react-native-google-mobile-ads pull request #572
Opened 2024-05-10 19:25 UTC by ds8k

### Description

`AdManagerAdRequest.Builder().addCustomTargeting` supports passing both strings and ArrayLists. iOS already handles this.

### Release Summary

- Add support for string[] in `customTargeting`

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

iOS ad loaded with strings and string[] in customTargeting:
![Screenshot 2024-05-10 at 2 58 04 PM](https://github.com/invertase/react-native-google-mobile-ads/assets/4458812/dcf05c7d-394d-4d33-87c8-f805f92bfd20)

Android
![Screenshot_20240510_152417_Axios](https://github.com/invertase/react-native-google-mobile-ads/assets/4458812/d0965f88-c0f4-45e3-a7dd-d95b121618ec)

2024-05-10 19:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/invertase/react-native-google-mobile-ads?pullRequest=572) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/invertase/react-native-google-mobile-ads?pullRequest=572) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/invertase/react-native-google-mobile-ads?pullRequest=572) it.</sub>

2024-05-13 07:00 UTC, dylancom requested changes

2024-05-13 07:00 UTC, dylancom commented on android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsCommon.java
> +        if (type.equals("String")) {
Instead of getting the type I believe you can just check if it's an instanceof String.
`if (value instanceof String) {`

2024-05-13 07:01 UTC, dylancom commented
Thanks for your PR! I requested a small change :)

2024-05-13 15:20 UTC, ds8k commented
@dylancom made that change

2024-05-13 16:15 UTC, merged

2024-05-13 16:15 UTC, dylancom commented
Thanks for your contribution!

2024-05-13 16:38 UTC, mikehardy commented
:tada: This PR is included in version 13.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-google-mobile-ads/v/13.3.0)
- [GitHub release](https://github.com/invertase/react-native-google-mobile-ads/releases/tag/v13.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: