feat(consent)!: migrate to UMP SDK
invertase/react-native-google-mobile-ads pull request #82
Opened 2022-02-26 01:21 UTC by birgernass

### Description

This PR replaces the legacy consent library with the new UMP SDK v2.
It is no longer possible to request the ad providers or to show a custom form.

There are also some platform inconsistencies I tried to resolve.
Please let me know if you see better ways to compromise:
* The consent status integer values are different on iOS and Android. I decided to return the respective string values instead.
* There is no equivalent for `UMPConsentInformation.sharedInstance.formStatus` on Android. I decided to return `isConsentFormAvailable` on both platforms, as the formStatus doesn't add much value as far as I'm concerned.

### Related issues

Fixes #38
Closes #43
Related to #64

### Release Summary

* changed `requestInfoUpdate` (new parameter & return type)
* changed `AdsConsentStatus` (string instead of integer)
* removed `showForm` (new parameter & return type)
* removed `addTestDevices` (see requestInfoUpdate)
* removed `setDebugGeography` (see requestInfoUpdate)
* removed `setTagForUnderAgeOfConsent` (see requestInfoUpdate)
* removed `getAdProviders`
* removed `getStatus`
* removed `setStatus`
* added `reset` method to reset state during debugging
* added optional `user_tracking_usage_description` key to `app.json` for ATT support

A library like [@iabtcf/core](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/core#iabtcfcore) can be used to parse the TCF string and evaluate the users consent choices.

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [X] Yes 🔥 
- My change supports the following platforms;
  - [X] `Android`
  - [X] `iOS`
- My change includes tests;
  - [X] `e2e` tests added or updated in `__tests__e2e__`
  - [X] `jest` tests added or updated in `__tests__`
- [X] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [X] Yes
  - [ ] No

### Test Plan

<p align="center">
<img width="700" alt="Screenshot 2022-02-25 at 22 16 07" src="https://user-images.githubusercontent.com/15228211/155822322-0cd0a58a-9f4d-4632-84a5-ccb4adf4dc3d.png"><br>
(The io.invertase.googleads package has since been updated.)
</p>
---

Think `react-native-google-mobile-ads` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

2022-02-26 01:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/invertase/react-native-google-mobile-ads?pullRequest=82) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/invertase/react-native-google-mobile-ads?pullRequest=82) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/invertase/react-native-google-mobile-ads?pullRequest=82) it.</sub>

2022-02-26 18:23 UTC, mikehardy requested changes
I added a bunch of nit-picky comments but in general this is an amazing advance for the module and none of my comments reflect anything serious.
I'll defer to @dylancom on whatever he has to say but I'm pretty much +1 on all of it.
Only thought I have is it might pay off (in terms of lower support via issues logged) to do a quick migration document indicating the path someone using the old style might take to adopt this one. Does that make sense, and if so is it possible - even if pretty rough / terse?

2022-02-26 18:23 UTC, mikehardy commented on ios/RNGoogleMobileAds/RNGoogleMobileAdsConsentModule.m
> +#endif
I don't believe this has been necessary for a long time - I think they can just all be one-liner `#import <React/RCTConvert.h>` style headers now?
I seem to recall a PR taking this conditional import stuff *out* of some other module recently even, where it was commented that it was an artifact of some long long gone react-native version

2022-02-26 18:23 UTC, mikehardy commented on ios_config.sh
> +  fi
@Salakar did you have any luck with the cocoapods add-plist functionality? I wonder if the reason we weren't using it before was the conditional JSON stuff, but ruby could probably handle it if you had a good result and maybe we could remove all this ios_config.sh machinery

2022-02-26 18:23 UTC, mikehardy commented on android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsConsentModule.java
> +      if (options.hasKey("testDeviceIdentifiers")) {
This is a nit-pick, but we're dereferencing options here without noting it is `@Nonnull` as a parameter annotation or testing it for null. Further on I can see at the typescript level you're verifying it is an object so this is probably safe and just a code style thing. I'd go with a `@Nonnull` annotation from androidx.annotations normally then, or leave it if that doesn't work

2022-02-26 18:23 UTC, mikehardy commented on docs/european-user-consent.mdx
> +The `AdsConsent` helper provides a promised based method to return the users consent status called `requestInfoUpdate`.
tiny grammar nitpick

```suggestion
The `AdsConsent` helper provides a promise based method to return the users consent status called `requestInfoUpdate`.
```

2022-02-26 18:23 UTC, mikehardy commented on docs/european-user-consent.mdx
> +The result of the method returns an `AdsConsentInfo` interface, which provides information about consent form availability and the users consent status:
```suggestion
The method returns an `AdsConsentInfo` interface, which provides information about consent form availability and the users consent status:
```

2022-02-26 18:23 UTC, mikehardy commented on docs/european-user-consent.mdx
> +If using a real device, ensure you whitelist it by passing the device ID, which can be obtained from native logs or using a library
```suggestion
If using a real device, ensure you add it to the list of allowed devices by passing the device ID, which can be obtained from native logs or using a library
```

2022-02-26 18:23 UTC, mikehardy commented on docs/european-user-consent.mdx
> +It is also possible to reset the UMP state for test devices. This does not reset the ATT state though.
> This does not reset the ATT state though

Hmm - any pointers for inexperienced devs here? How does one reset the ATT state? Maybe a link to an apple doc or similar...

2022-02-26 18:23 UTC, mikehardy commented on src/types/AdsConsent.interface.ts
> +   * An array of test device IDs to whitelist.
```suggestion
   * An array of test device IDs to allow.
```

2022-02-26 19:58 UTC, birgernass commented
> I added a bunch of nit-picky comments but in general this is an amazing advance for the module and none of my comments reflect anything serious. I'll defer to @dylancom on whatever he has to say but I'm pretty much +1 on all of it. Only thought I have is it might pay off (in terms of lower support via issues logged) to do a quick migration document indicating the path someone using the old style might take to adopt this one. Does that make sense, and if so is it possible - even if pretty rough / terse?

Happy to hear! And thank you for the suggestions. Also makes a lot of sense to add a bit more context for the migration. I'll write something up. Should it be part of the web docs or just added to the change log or what did you have in mind?

2022-02-26 22:04 UTC, mikehardy commented
> > I added a bunch of nit-picky comments but in general this is an amazing advance for the module and none of my comments reflect anything serious. I'll defer to @dylancom on whatever he has to say but I'm pretty much +1 on all of it. Only thought I have is it might pay off (in terms of lower support via issues logged) to do a quick migration document indicating the path someone using the old style might take to adopt this one. Does that make sense, and if so is it possible - even if pretty rough / terse?
> 
> Happy to hear! And thank you for the suggestions. Also makes a lot of sense to add a bit more context for the migration. I'll write something up. Should it be part of the web docs or just added to the change log or what did you have in mind?

I think it makes sense as a file in the docs area that goes to the web docs. That way it can also be easily changed/improved by anyone that tries it later, changelogs end up being kind of immutable / irritating to change

2022-02-26 22:10 UTC, mikehardy approved these changes
Thanks for the quick turnaround!
I'm curious if Mike Diarmid (Salakar) has input on the ios_config thing but that is legitimately a different PR really if he does, so no need to block on it.
I'm +1 on this then but will defer to Dylan in case he sees something I missed (I always miss something)

2022-02-27 08:53 UTC, dylancom commented
Awesome work! Will have time tomorrow to check this out.

2022-02-27 21:58 UTC, mikehardy commented
I read the migration doc - I'm still +1 or now I guess I'm +2 because I think that will help a lot, and now if/when there is confusion people can post PRs to that doc as they work through it in case anything isn't clear. Gives us some place to point though as the inevitable issues will come in with "help what happened to AdConsent !?!"  ;-)

2022-02-28 12:54 UTC, dylancom approved these changes

2022-02-28 12:54 UTC, dylancom commented
Looking good to me!

2022-02-28 13:41 UTC, merged

2022-02-28 13:47 UTC, mikehardy commented
I had contemplated batching a Swift/Kotlin migration at the same time as this as one major version but I prefer to keep changes more incremental with regard to version numbers if possible. I really don't mind bumping major version but I like the versions themselves to be focused and hopefully stable. Mixing in a code migration at the same time as this release would go against that I think, so...thinking of just releasing this. Any objections? 

Maybe we can do one PR first to add this functionality to the example, and/or someone could test integrate it in their app to give it some semi-production use prior to full release? yarn lets you rely on the commit hash fa88240d937499b4a570c40914f06054dfa31b89 and if you add a prepare phase where you cd into the directory and yarn / yarn build it should be possible to depend on this from source at the commit point (that's a supported feature - building from source via commit ref - please holler if it does not work!)

2022-03-02 21:48 UTC, birgernass commented
@mikehardy I prepared a [test case](https://github.com/birgernass/react-native-google-mobile-ads/commit/a9c03aeaebad233d96b77585c7b3df9abbc16149) that works with a real app ID, but doesn't work with the test app ID as the consent form needs to be configured in the AdMob backend.

I also can't run a production test at this point as we depend on a custom Ad Manager wrapper and I don't want to ship another library just to test it.

2022-03-03 20:45 UTC, mikehardy commented
:tada: This PR is included in version 5.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-google-mobile-ads/v/5.0.0)
- [GitHub release](https://github.com/invertase/react-native-google-mobile-ads/releases/tag/v5.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: